### ISSUE TITLE
What is the speed of PyramidBox?

### ISSUE THREAD

**Issue by YueXiNPU** [PaddlePaddle/models#1272]
Dear Professor
       I am a Ph.D Student from NPU and interested in your PyramidBox. With the help of @qingqing01, we manage to run the eval code. Many thanks to him. 
       In our experiment, it will take about 1.37s to eval an image. So, I check the paper about PyramidBox but fail to find experiments about the analysis of model speed. 
       Would you like to share something about model speed?

**Comment by qingqing01** [comment]
him -> her   :)


Some our profiling:

Env:
  - CUDA 8.0 + cuDNN  7.0  + Tesla P40
  - batch size: 5/per gpu
  - input data: 3 x 640 x 640

Use PyReader and Python multiprocess to preprocess dataset.

The training time:

|Experiment | GPU count | BatchSize/per gpu | images/second  | speed|
|:---|:---:|:---:|:---:|:---:|
|Executor | 1 | 5 |2.738|1|
|ParallelExe|2 | 5 |4.838|1.767|
|ParallelExe|4|5|7.163|2.616|
|ParallelExe|8|5| 12.563|4.588|


Since the evaluation uses multi-scale and pyramid evaluation methods, it is slowly, more than one hours to eval all validation dataset on one P40, about 1.9s per image.

https://github.com/PaddlePaddle/models/blob/d65c9edf54bd70e0764bb9279bf84c792d2af093/fluid/face_detection/widerface_eval.py#L61-L66

But for the inference,  you can remove the multi-scale and pyramid evaluation methods, it will be faster.

**Comment by YueXiNPU** [comment]
Thank you @qingqing01 for your hard work. This model has the amazing performance in face detection.
