### ISSUE TITLE
CTR model例子，id字段不适合选作特征吧？

### ISSUE THREAD

**Issue by superzhangmch** [PaddlePaddle/models#153]
CTR model这个例子中：
https://github.com/PaddlePaddle/models/blob/develop/ctr/dataset.md
选用了id这个字段。
经过统计，dataset大小是40428967， id的不同取值个数是40428967个。也就是说每一个样本都有一个不同的id。
那么还用这个id作为特征，不合适吧？

**Comment by Superjomn** [comment]
原始的是用 mod 来控制 id 的数目， 比如控制id的数目为 1000，那么 4亿的 id % 1000，也就剩 1000 个id了

**Comment by superzhangmch** [comment]
id 数和数据集大小一样，那么这个id其实相当于就像是数据库里的连续递增id（而且看到数据集中该字段确实是递增id，只是不是连续）。那么这样的特征应该对效果提升没啥用吧
否则，我自己也造这么几个字段，岂不是也能提升效果。

**Comment by Superjomn** [comment]
这里是一个内存方面的优化，无论多么大的ID空间，都可以规约到内存能够容纳的大小，如果一定需要id对等，那构建数据时，把特定特征对应的ID数设置成原始的ID便可以了。

连续的ID  -> mod 规约 -> 也应该是连续的吧，这个trick应该影响不太大
@superzhangmch

**Comment by Superjomn** [comment]
update下，CTR中的确有一些问题，现在是跟demo的数据耦合的，不太科学。

https://github.com/Superjom/models-1/tree/ctr2/ctr

这个解决了数据格式的问题，还在过PR，这种会陆续修改各种问题 merge进来。

可以先试用这个，ID化等预处理现在是用户自己做的，所以mod与否也跟model没有关系了。
@superzhangmch

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
