### ISSUE TITLE
ctr（wide&deep）模型的dense部分是否可以通过特征slot号进行embedding

### ISSUE THREAD

**Issue by awper361** [PaddlePaddle/models#165]
@Superjom

**Comment by Superjomn** [comment]
现在是 FC 模拟的

```python
        dnn_embedding = layer.fc(
            input=self.dnn_merged_input, size=dnn_layer_dims[0])
```

**Comment by awper361** [comment]
fc模拟的意思是，现在就是fc对吧。暂时还不支持slot embedding。

**Comment by Superjomn** [comment]
可以啊，稍微改下就行。

用FC模拟因为简单，多层DNN所有的都是FC，用一个 dim list 就可以定义每层FC的维度。

目前是：

dim list:  [512, 256, 64] -> embedding 512维，外加2层FC，维度分别为 256, 64

**Comment by awper361** [comment]
如果dim list: [512, 256, 64]，那么第一层应该是one-hot fc 512对吧。
我的需求是，第1个slot的特征值只会落在embedding层的第一个元素上

**Comment by Superjomn** [comment]
FC 和 Embedding 在原理上是完全等价的

如果对slot-> embedding 的控制有需求：

可以把slot 映射到同一个ID？

模型这边，一个ID对应一个 embedding vector这是固定的，但ID的处理用户可以随意控制，对映射的需求应该放在ID产生这步预处理上。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
