### ISSUE TITLE
Paddle/DeepSpeech2 数据读入上的一些问题

### ISSUE THREAD

**Issue by lispc** [PaddlePaddle/models#230]
# 问题描述
在这个 repo 的 DeepSpeech2 代码中，应用层的 _padding_batch 函数，框架层的
 feeder 和 gradient_machine.forwardBackward 是在一个线程顺序做的。这种方案在速度上，不是最优的。因为前两者耗时较大(都是需要0.3s量级的事情)，而且本来可以 pipeline 地并行做掉。

# 我的方案
## 方案概述
Step 1: 把 DataFeeder 拆成两部分，第一部分是 list of ndarrays to one big ndarray，第二部分是 the final ndarray to paddle.argument
Step 2: 把 instance 的 reading 和 processing, batch 的 padding, 和刚才拆出来的 DataFeeder 第一部分(list of ndarrays to one big ndarray)放在第一个**进程**中，把生成的 ndarray 训练数据通过 pipe 传递到第二个进程，第二个进程从 pipe 读数据，然后做训练。
## 设计原因
我的方案几个设计上的考虑：
1. 分进程的原因：担心 GIL
2. 拆 Feeder 的原因：ndarray 可以从 pipe 用 pickle 传递，但是 paddle.argument 不能跨进程传递

## 操作方式
把框架层的代码(trainer.py, data_feeder.py, dataprovider_converter.py)拷贝到应用层，然后做了很多修改。
## 实验结果 
我测试我的这份加速代码的结果：单batch平均(第10个到第20个)从2.5s下降到1.8s(很接近forwardbackward时间了)，其中 reader + feeder 时间 从 0.65s 降低到 0.15s。端到端加速1/3，效果明显。
# 汇总观点
1. 现在 Paddle DataFeeder 的设计可能是有问题的，在框架层面限制一块挺大的计算量必须在 forward/backward 前完成，对速度影响较大。
2. 现在 DS2 batch_reader 里面的 padding 也是在 forward/backward 线程做的，这个倒是可以在应用层而不是框架层直接改掉。

可以一起讨论一下观点～

**Comment by xinghai-sun** [comment]
感谢你的关注和很好的建议！！

你的关注和我们之前profiling的结论基本一致，以下是我们之前内部的聊天记录：

”7%的时间用于数据处理（抽特征用异步xmap几乎不花时间，主要是batch的padding操作未并行化），12%的时间用于feeder调用（numpy数据转化并传入c++），剩下81%是forward-backward。”

即两处优化点：
- Paddle自身的 DataFeeder 的设计
- DS2 的 _padding_batch 函数以 pipeline方式优化（目前仅instance preprocess 以 pipeline并行化，但尚未在batch 层面做）

根据我们自己测试结果，如果这两部分优化做完后最佳情况下可以加速20%。和你测的30%也比较接近。

非常期待你能分享或者贡献你的修改，或者设计建议！

**Comment by xinghai-sun** [comment]
The second part (_padding_batch pipeline) is fixed with PR: https://github.com/PaddlePaddle/models/pull/231. Please review.

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
