### ISSUE TITLE
图像分类的例子如何单机多卡进行训练

### ISSUE THREAD

**Issue by Sampson1107** [PaddlePaddle/models#302]
请问在如下目录下，执行修改train.py的如下行：
```python
paddle.init(use_gpu=True, trainer_count=1)为
paddle.init(use_gpu=True, trainer_count=4)
```
是否可以在四个卡上数据并行训练？
若可以，我设置的batch_size=1024，是四个卡总的batch_size,还是单卡的batch_size呢？
在这个目录下我仅仅修改了如下注释行(训练和测试部分)：
```python
flowers.train()
```
为
```python
 reader.train_reader('train.list')
```
和num_classes实现了在imagenet数据集上的训练，是否可行？
期待您的回复。

**Comment by Sampson1107** [comment]
看显存的使用情况，batch应该是四个卡的batch，这样简单的修改在四个卡上数据并行，是否正确呢？

**Comment by lcy-seso** [comment]
- 您好，您理解的没有错。trainer_count=4 会使用单机4卡进行训练。
- batch size 中设置的mini-batch大小这么多个样本，会平均地分配到4块卡上。
- 您的修改是正确的。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
