### ISSUE TITLE
Update the documentation of "How to use CAPI" in PaddleModel repo.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/models#372]
- 我们计划在 models repo 的 [`how_to_use_capi`](https://github.com/PaddlePaddle/models/tree/develop/how_to_use_capi) 目录下增加更加丰富的，与CAPI使用相关的文档和例子，保证能够覆盖到 PaddlePaddle 所有输入数据类型。
- 在这个issue 中，先提出我们能够想到的，需要包含的最小信息。请大家不吝提出更好的建议，帮助我们做好“CAPI使用”相关的文档和例子。
- `how_to_use_capi` 会含有二级目录，对应不同的可以完整运行的示例代码；
- 一级目录下的 README 需要介绍与CAPI使用相关的通用信息。
- 以下是关于一级目录下 README 的一个基础提纲：
---

### 2. CAPI 使用流程指南
1.  序列化模型配置；
2. 组织数据数据；
3. 初始化/加载模型；
4. 前向计算；
5. 清理；

### 3. 从python 用户接口的输入数据类型，到 C++ 端输入数据类型对应

- 首先，需要一个`[ 12 x 2]` 的表格，第一列是用户在 python 端看到的，PaddlePaddle 支持的所有 12 种输入数据类型；第二列对应了 12 种输入数据在 C++ 代码中如何组织的tips。
- 关键代码片段和一定的解释说明；

### 5. F&Q

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
