### ISSUE TITLE
Transformer based neural machine translation for high-performance inference

### ISSUE THREAD

**Issue by xptree** [PaddlePaddle/models#3727]
Hi, I notice that you have released Transformer based NMT model at https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/neural_machine_translation/transformer. Excellent work!!!

I want to try the current model in production which has high QPS requirement. I wonder if PaddlePaddle has any plan to release a Transformer based NMT model for high performance inference, just like what you have done for PaddleDetection (https://github.com/PaddlePaddle/models/pull/3529).

Any help will be appreciated.

**Comment by xptree** [comment]
BTW, my current plan is to switch my production environment to TensorRT. But I am still interested in how to do efficient inference with PaddlePaddle.

**Comment by guoshengCS** [comment]
Baidu Translation uses PaddlePaddle as backend for online inference truely. While some works for high QPS requirement have been done but have not been ready to be released. Just like what [Faster Transformer](https://zhuanlan.zhihu.com/p/73715272) does, kernel fusion is the key point. However more fusion must be done since the small data size at each beam search step for decoding, actually MultiHeadAttention is implemented by one CUDA kernel. 8-bit post-training quantization also helps for high QPS without BLEU decay.

Thanks for your attention.

**Comment by xptree** [comment]
@guoshengCS Thanks for your prompt reply and for providing the technical details. I will definitely try them in my case.

Please let me know when Baidu Translation Team decides to release related code in the future. I believe this will make a huge impact on both industry and academia.
