### ISSUE TITLE
图片分类各batch的错误率差距极大

### ISSUE THREAD

**Issue by yuanghbdbj** [PaddlePaddle/models#733]
使用image_classification中alexnet做2分类，在demo的基础上做了如下改动：1）自己的样本，量较少，不到3000，且样本未打乱但保留了shuffle；2）调整学习率至0.0001（0.001训练会失败）。

出现错误率稳定在某几个batch特别低，其他batch的错误率很高，且多个pass后仍然是这种情况，请问有可能是什么问题呢？
pass1的部分日志：
![default](https://user-images.githubusercontent.com/36145868/37385595-8aef191c-278f-11e8-9802-66f3e0f15e4b.png)
pass75的部分日志：
![default](https://user-images.githubusercontent.com/36145868/37385624-a1552660-278f-11e8-9685-78ec12ab8e73.png)

**Comment by yuanghbdbj** [comment]
另外，在这之前试过3分类：1）但样本比例差距大，近似4:4:1，样本未打乱且未使用shuffle；2）学习率0.001。出现以下问题：
1、到第二个pass便失败了，报错如下：
![default](https://user-images.githubusercontent.com/36145868/37385953-4a8a33fa-2791-11e8-87c6-5988d486cb92.png)
2、pass0各batch error出现震荡，甚至到0和1
![default](https://user-images.githubusercontent.com/36145868/37385982-6df8f718-2791-11e8-97c0-9b55ba816ca8.png)

**Comment by yeyupiaoling** [comment]
@yuanghbdbj 
出现的那个错误是浮点异常，减小学习率等改变超参数的方式可以解决。对于你这个batch的错误率差距极大我也想不到什么问题，也行这篇文章能帮到你：https://blog.csdn.net/qq_33200967/article/details/79095265

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
