### ISSUE TITLE
跑了下ltr model的例子， ranknet的网络收敛，可是lambda rank的网络从loss看根本不收敛

### ISSUE THREAD

**Issue by everal** [PaddlePaddle/models#817]
最近在考虑ltr model的使用，尤其是listwise的方式。
试了下paddle提供ranknet和lambda_rank两个模型(没做任何修改)，发现lambda_rank方式下cost并没有表现出减小的趋势，完全是无规律震荡的(如下图)。 于是又跑了下ranknet的模型，发现结果是收敛的。
请教下，pairwise和listwise的方式，理论上效果上是几乎相等的，但为何在训练结果上的差别如此大？是因为部分超参并没有选好么？
辛苦相关同学解答下。
![image](https://user-images.githubusercontent.com/7055728/38467415-cfa3f96c-3b6a-11e8-9779-29956ef4ba2f.png)

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
