### ISSUE TITLE
相同测试集，使用infer预测准确率与evaluator评估准确率差距较大

### ISSUE THREAD

**Issue by liaibao120** [PaddlePaddle/models#865]
在使用paddle-v2版本时，遇到一个问题。
描述下问题：基于nested_sequence/text_classification 的双序列文本分类模型。相同一批测试数据集，在模型训练时，最后一轮的评估结果'classification_error_evaluator': 0.0109，但使用训练好的模型，使用infer接口去预测该批测试数据时，准确率只有79%，比模型训练时的评估结果低了很多。
想请教下，这种情况是怎么造成的呢？该如何排查原因呢

**Comment by jacquesqiao** [comment]
最后一轮的评估用的是一个batch的数据，还是用的所有的测试数据？

**Comment by liaibao120** [comment]
关键代码如下：
test_reader = paddle.batch(
                paddle.reader.shuffle(
                    reader.train_reader(test_data_dir, word_dict, label_dict),
                    buf_size=conf.buf_size),
                batch_size=conf.batch_size)
buf_size=10000, batch_size=1000
result = trainer.test(reader=test_reader, feeding=feeding)
logger.info("Test at Pass %d, %s \n" % (event.pass_id, result.metrics))

不太了解内部机制，不知道这样的配置，在评估时是使用的一个batch的数据，还是读取的全部的测试数据

**Comment by liaibao120** [comment]
参数配置文件
[config.txt](https://github.com/PaddlePaddle/models/files/1920665/config.txt)
网络配置文件
[network_conf.txt](https://github.com/PaddlePaddle/models/files/1920667/network_conf.txt)
训练逻辑代码
[train.txt](https://github.com/PaddlePaddle/models/files/1920669/train.txt)
预测逻辑代码
[infer.txt](https://github.com/PaddlePaddle/models/files/1920670/infer.txt)

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
