### ISSUE TITLE
SSD 模型训练过程中 test mAP提示并不准确

### ISSUE THREAD

**Issue by HUSTGOC** [PaddlePaddle/models#871]
RT，通过设置 ssd 模型 pic size 为300 * 300  训练1280*720 的图片，然后通过400多轮的迭代训练，test 的 mAP稳定在95左右。

然后我从训练的时候的测试集合随机挑选了5张图片进行验证，发现很多识别错误和漏识别，正确率只有50%左右。

难道是我哪里做错了？

**Comment by HUSTGOC** [comment]
![image](https://user-images.githubusercontent.com/13493253/39109994-f038c58e-4701-11e8-8e09-e21f6374b812.png)
这个文件没有找到呀？  在哪有

**Comment by Yancey0623** [comment]
> 这个文件没有找到呀？ 在哪有

是 https://github.com/PaddlePaddle/models/blob/develop/ssd/config/pascal_voc_conf.py 这个文件, 文档没有更新。

> 然后我从训练的时候的测试集合随机挑选了5张图片进行验证，发现很多识别错误和漏识别，正确率只有50%左右。

可以用和训练时一样的test数据跑下看看结果？

**Comment by HUSTGOC** [comment]
我就是用的训练的时候的测试集跑的结果进行人工测试的

**Comment by Yancey0623** [comment]
是根据 https://github.com/PaddlePaddle/models/blob/develop/ssd/infer.py 这个脚本来测试的吗？另外为了保证变量可控，不如选取一个pass保存的model，然后用同样的测试集去跑下测试呢？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
