### ISSUE TITLE
sequence slice

### ISSUE THREAD

**Issue by yttbgf** [PaddlePaddle/models#893]
请问一个序列长度N，维度为M，需要从中挑出指定序列位置（跟具体样本没关系，预先知道）的一些元素，维度不切片，怎么操作最简单？看了v2的api seq_slice sub_nested_seq都需要给出索引，这些索引不能是预定义好的python List，必须是paddle.v2.config_base.Layer，如果需要从reader的generator给出的话，应该怎么提供？用dense_vector不work,要用dense_array？

**Comment by qingqing01** [comment]
- sub_seq:  http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#sub-seq
- seq_slice: http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#seq-slice
- sub-nested-seq: http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#sub-nested-seq


有这些挑选sub序列的层，可以按照你的需求选择。其中

1. `sub_seq`的`offsets`, `sizes`输入都是layer，可以是data_layer，从源码来看，是 `integer_sequence`类型。 reader返回的`[int]`类型。
2. `seq_slice`参考： https://github.com/PaddlePaddle/models/blob/develop/globally_normalized_reader/model.py#L249
3. `sub_nested_seq`参考： https://github.com/PaddlePaddle/models/blob/develop/globally_normalized_reader/model.py#L249

**Comment by lcy-seso** [comment]
如果对seq_slice使用有疑问，请看这个示例是否有帮助： https://github.com/lcy-seso/paddle_example/tree/master/seq_slice_demo

这里有可运行的程序： https://github.com/lcy-seso/paddle_example/blob/master/seq_slice_demo/test_seq_slice.py

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
