### ISSUE TITLE
deepFM 不定长特征处理

### ISSUE THREAD

**Issue by dpwu1994** [PaddlePaddle/models#946]
模型库里的deepFM的特征都是固定长度的，对于不定长的特征，在deepFM的deep部分，是否需要对这些不定长特征做一下padding。在网上搜索的话，发现deepFM对于这种case做了padding，但是我目前是以这个格式type=paddle.data_type.integer_value_sequence(sparse_feature_dim))输入，然后做一个pooling，发现可以运行。所以模型库里的deepFM对于这种不定长的特征建议以哪种方式处理？

**Comment by kuke** [comment]
对于不定长的输入，一般是要做padding的

**Comment by dpwu1994** [comment]
因为不做padding的话，发现type=paddle.data_type.integer_value_sequence(sparse_feature_dim))输入也能正常训练，做padding的话应该用那种格式输入，这两种之间又有什么区别呢？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
